blank_issues_enabled: false
contact_links:
  - name: GitHub Actions documentation
    url: https://docs.github.com/actions
    about: Check official product documentation for general GitHub Actions questions.
